<a href="https://colab.research.google.com/github/dimamagdenko07-spec/python-data-analysis-olist/blob/main/notebooks/python_lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание 1

In [ ]:
import pandas as pd
import numpy as np

orders = pd.read_csv('olist_orders_dataset.csv')
time = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]
'''Преобразуем даты'''
for col in time:
  orders[col] = pd.to_datetime(orders[col])
display(orders)
indexed_orders = orders.copy()
indexed_orders.set_index('order_purchase_timestamp', inplace = True)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [ ]:
'''Считаем, сколько дней прошло с момента покупки до момента доставки'''
df = indexed_orders.dropna(subset=['order_approved_at', 'order_delivered_customer_date']).copy()
start_days = df['order_approved_at'].values.astype('datetime64[D]')
end_days = df['order_delivered_customer_date'].values.astype('datetime64[D]')

df['time_days'] = np.busday_count(start_days, end_days)
df.to_csv('table_with_days.csv')
display(df)

,order_id,customer_id,order_status,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,time_days
order_purchase_timestamp,,,,,,,,
2017-10-02 10:56:33,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,6
2018-07-24 20:41:37,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,8
2018-08-08 08:38:49,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,7
2017-11-18 19:28:06,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,10
2018-02-13 21:18:39,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,3
...,...,...,...,...,...,...,...,...
2017-03-09 09:54:05,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,6
2018-02-06 12:58:58,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,16
2017-08-27 14:46:43,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,18
2018-01-08 21:28:27,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,13
2018-03-08 20:57:30,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,5

In [ ]:
'''Смотрим на просроченные товары'''
indexed_orders['is_delayed'] = indexed_orders['order_delivered_customer_date'] > indexed_orders['order_estimated_delivery_date']
'''Смотрим процент просроченных товаров в месяце'''
delay_mean = indexed_orders['is_delayed'].resample('MS').mean() * 100
max_delay_month = delay_mean.idxmax()
max_delay_percent = delay_mean.max()
display(indexed_orders)
indexed_orders.to_csv("prod.csv")
print("Месяц с максимальным процентов просроченных заказов: ", max_delay_month)
print("Процент просроченных заказов в этот месяц: ", max_delay_percent)

,order_id,customer_id,order_status,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,is_delayed
order_purchase_timestamp,,,,,,,,
2017-10-02 10:56:33,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,False
2018-07-24 20:41:37,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,False
2018-08-08 08:38:49,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,False
2017-11-18 19:28:06,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,False
2018-02-13 21:18:39,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,False
...,...,...,...,...,...,...,...,...
2017-03-09 09:54:05,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,False
2018-02-06 12:58:58,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,False
2017-08-27 14:46:43,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,False
2018-01-08 21:28:27,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,False
2018-03-08 20:57:30,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,False

Месяц с максимальным процентов просроченных заказов:  2016-09-01 00:00:00
Процент просроченных заказов в этот месяц:  25.0

Задание 2

In [ ]:
items = pd.read_csv('olist_order_items_dataset.csv')
'''Сливаем цену и время покупки по индексу заказа '''
df_price = pd.merge(orders[['order_id', 'order_purchase_timestamp']], items[['order_id', 'price']], on='order_id')
'''Устанавливаем время покупки индексом и группируем по датам(создавая пропущенные дни)'''
days = df_price.set_index('order_purchase_timestamp')['price'].resample('D').sum()
days.to_csv("days.csv")
display(days)

order_purchase_timestamp
2016-09-04     72.89
2016-09-05     59.50
2016-09-06      0.00
2016-09-07      0.00
2016-09-08      0.00
               ...
2018-08-30      0.00
2018-08-31      0.00
2018-09-01      0.00
2018-09-02      0.00
2018-09-03    145.00
Freq: D, Name: price, Length: 730, dtype: float64

In [ ]:
df_price['weekday'] = df_price['order_purchase_timestamp'].dt.day_name()
df_price['hours'] = df_price['order_purchase_timestamp'].dt.hour
'''Смотрим в какое время у нас продаётся больше товаров каждый день'''
table = df_price.pivot_table(
    index='weekday',
    columns='hours',
    values='order_id',
    aggfunc='count'
    )
table.to_csv('intraday_pattern.csv')
peaks = table.idxmax(axis=1)
days_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
peaks = peaks.reindex(days_week)
display(peaks)

weekday
Monday       14
Tuesday      14
Wednesday    14
Thursday     16
Friday       16
Saturday     19
Sunday       20
dtype: int32

Задание 3

In [ ]:
'''Считаем кумулятивную выручки с самого начала по сегодняшний день'''
days_rolling = days.groupby(days.index.year).expanding().sum()

days_rolling = days_rolling.reset_index(level=0, drop=True)
'''Считаем скользящее среднее и скользящее стандартное отклонение за 30 дней и ищем аномалии'''
rolling_mean = days.rolling(30).mean()
rolling_std = days.rolling(30).std()
Z = (days - rolling_mean) / rolling_std
anomalies = Z[Z>3]
Z.to_csv('z_score.csv')
display(Z)

order_purchase_timestamp
2016-09-04         NaN
2016-09-05         NaN
2016-09-06         NaN
2016-09-07         NaN
2016-09-08         NaN
                ...
2018-08-30   -1.849475
2018-08-31   -1.688325
2018-09-01   -1.551730
2018-09-02   -1.436969
2018-09-03   -1.325890
Freq: D, Name: price, Length: 730, dtype: float64

Задание 4

In [ ]:
'''Доход за последние 7 дней, не считая этот'''
revenue_last_7d = days.shift(1).rolling(7).sum()
'''Доход за неделю до этой недели'''
revenue_prev_7d = days.shift(7).rolling(7).sum()
'''Считаем относительный темп'''
wow_growth = (revenue_last_7d - revenue_prev_7d) / revenue_prev_7d * 100

print(wow_growth)
'''Ищем набольшие падения в доходе'''
biggest_drops = wow_growth.nsmallest(3)
print(biggest_drops)

order_purchase_timestamp
2016-09-04          NaN
2016-09-05          NaN
2016-09-06          NaN
2016-09-07          NaN
2016-09-08          NaN
                ...
2018-08-30   -68.890537
2018-08-31   -75.335382
2018-09-01   -79.676202
2018-09-02   -85.259877
2018-09-03   -89.141024
Freq: D, Name: price, Length: 730, dtype: float64
order_purchase_timestamp
2016-09-23   -100.0
2016-09-24   -100.0
2016-09-25   -100.0
Name: price, dtype: float64